# Makefile dành riêng cho Windows (MSYS2 / MinGW-w64)
TARGET = space_shooter.exe

CC = gcc

SDL_CFLAGS = $(shell sdl2-config --cflags)
SDL_LIBS = $(shell sdl2-config --libs)

FT_CFLAGS = $(shell pkg-config --cflags freetype2)
FT_LIBS = $(shell pkg-config --libs freetype2)

# Tổng hợp CFLAGS và LIBS
CFLAGS = -Wall $(SDL_CFLAGS) $(FT_CFLAGS) -Iinclude
# -mwindows để ẩn cửa sổ console (Cmd) khi chạy game
LIBS = $(SDL_LIBS) $(FT_LIBS) -lm -lws2_32 -mwindows

SRCS = src/main.c src/utils.c src/data.c src/admin.c src/player.c src/story.c src/ui.c src/timer.c src/network.c src/graphics.c

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(SRCS) -o $(TARGET) $(CFLAGS) $(LIBS)
	@echo "=> Bien dich cho Windows thanh cong!"

clean:
	rm -f $(TARGET)
